# -*- coding: utf-8 -*-
"""Credit card fraud detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kBv2e1T2oY-JgjGSJ23PgdsHKqosYRNQ
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#Loading the dataset
credit_card_data = pd.read_csv('/content/creditcard.csv')

credit_card_data.shape

#Exploring the Dataset-First 5 columns
credit_card_data.head()

#Exploring the Dataset-Last 5 columns
credit_card_data.tail()

#Dataset Information-We can see that no null values are there
credit_card_data.info()

credit_card_data.isnull().sum()
#There are no missing values in this dataset

#Distribution of legit and fraudulent transactions
#0->Legit transactions and 1->fraudulent transactions
credit_card_data['Class'].value_counts()

"""The dataset is highly unbalanced
0-> Normal transaction
1->Fraudulent transaction
"""

#Separating the Data for Analysis
legit= credit_card_data[credit_card_data.Class==0]
fraud=credit_card_data[credit_card_data.Class==1]

print(legit.shape)
print(fraud.shape)

"""Statistical measures of the Data"""

legit.Amount.describe()
#We can see that the mean amount of legit transactions is 88$ nearly

fraud.Amount.describe()
#We can see that the mean amount of fraudulent transactions is 122$, which is much higher than mean transaction amount of legit transactions

#Comparing the values of both legit and fraud transactions
credit_card_data.groupby('Class').mean()

"""Since the Data is quite unbalanced -90% of the data lies in legit transaction and only 10% for fraud transaction, we are using Undersampling"""

#Building a Sample Dataset containing similar distribution of normal and fraudulent transactions
#Taking randomly 492 samples from Legit transaction to create a balanced dataset

legit_sample = legit.sample(n=492)

"""Concatening both Legit and Fraud dataframes row wise"""

New_dataset = pd.concat([legit_sample,fraud],axis=0)

New_dataset.head()

New_dataset.tail()

New_dataset['Class'].value_counts()
#Verifying the size of our New dataset- its evenly balanced now

New_dataset.groupby('Class').mean()
# Mean remains similar even now for fraud transactions after undersampling as well.

"""Splitting the Data into features and targets"""

X= New_dataset.drop(columns = 'Class',axis =1)
Y= New_dataset['Class']

X.head()
#Column Class is dropped from X now

print(Y)
#Y has Class with both legit and fraud values

"""Splitting the data into Training and Testing data"""

X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size = 0.2,stratify=Y,random_state=2)

#Checking the shape and distribution of X training and testing data
print(X.shape,X_train.shape,X_test.shape)

#Checking the shape and distribution of Y training and testing data
print(Y.shape,Y_train.shape,Y_test.shape)

"""Model Training

To tackle the convergence issue , we are scaling the dataset
"""

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

#Training on scaled Data

model=LogisticRegression(max_iter=1000,solver='liblinear',class_weight='balanced')
model.fit(X_train_scaled,Y_train)

"""Model Evaluation"""

#Accuracy on training data
X_train_prediction= model.predict(X_train_scaled)
training_data_accuracy= accuracy_score(X_train_prediction,Y_train)

print('Accuracy on training data:', training_data_accuracy)

#Checking Accuracy on test data
X_test_prediction = model.predict(X_test_scaled)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

print('Accuracy on test data:', test_data_accuracy)

"""Predicting Values for Test set"""

from sklearn.metrics import classification_report, confusion_matrix

Y_pred=model.predict(X_test_scaled)

print(confusion_matrix(Y_test,Y_pred)) #Prediction vs Reality

print(classification_report(Y_test,Y_pred))

"""Visualization"""

import seaborn as sns
import matplotlib.pyplot as plt

cm=confusion_matrix(Y_test,Y_pred)

sns.heatmap(cm,annot=True,fmt='d',cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion matrix")
plt.show()

